- src/StackExchange.Redis.Extensions.Core/ISerializer.cs
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- src/StackExchange.Redis.Extensions.Jil/JsonSerializer.cs
- src/StackExchange.Redis.Extensions.Newtonsoft/JsonSerializer.cs
- tests/StackExchange.Redis.Extensions.Tests/Helpers/TestItemSerializer.cs
As per the opened issue #2, this is the change from text-based ISerializer to binary.
Now the serializer produces `byte[]` instead of `string` and deseralized from `byte[]`.
I've run the existing tests and they are green.
Obviously this breaks any backwards compatibility but I don't know if this is an issue.
Fixes #2.
> Change ISerializer from text-based to binary-based.

- src/StackExchange.Redis.Extensions.Core/Configuration/IRedisCachingConfiguration.cs
- src/StackExchange.Redis.Extensions.Core/Configuration/RedisCachingSectionHandler.cs
- src/StackExchange.Redis.Extensions.Core/Configuration/RedisHost.cs
- src/StackExchange.Redis.Extensions.Core/Configuration/RedisHostCollection.cs
- src/StackExchange.Redis.Extensions.Core/StackExchange.Redis.Extensions.Core.csproj
- tests/StackExchange.Redis.Extensions.Tests/App.config
- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
- tests/StackExchange.Redis.Extensions.Tests/StackExchange.Redis.Extensions.Tests.csproj
Example usage;
```xml
<configSections>
<section name="redisCacheClient"
type="StackExchange.Redis.Extensions.Core.Configuration.RedisCachingSectionHandler, StackExchange.Redis.Extensions.Core" />
</configSections>
<redisCacheClient allowAdmin="true" ssl="false" connectTimeout="5000">
<hosts>
<add host="127.0.0.1" cachePort="6379"/>
</hosts>
</redisCacheClient>
```
Code behind;
```csharp
IRedisCachingConfiguration configuration = RedisCachingSectionHandler.GetConfig();
ConfigurationOptions options = new ConfigurationOptions
{
Ssl = configuration.Ssl,
AllowAdmin = configuration.AllowAdmin
};
foreach (RedisHost redisHost in configuration.RedisHosts)
{
options.EndPoints.Add(redisHost.Host, redisHost.CachePort);
}
var connectionMultiplexer = ConnectionMultiplexer.Connect(options);
```
> Implement basic redis client configuration section

- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
The existing implementation Flushes all database. By applying the changes only the specified database will be flushed.
> [FIX] Flush only specified Redis database

- .nuget/NuGet.Config
- src/StackExchange.Redis.Extensions.Core/ICacheClient.cs
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- src/StackExchange.Redis.Extensions.Jil/JilSerializer.cs
- src/StackExchange.Redis.Extensions.Newtonsoft/CachedObject.cs
- src/StackExchange.Redis.Extensions.Newtonsoft/NewtonsoftSerializer.cs
- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
- tests/StackExchange.Redis.Extensions.Tests/Helpers/TestClass.cs
- tests/StackExchange.Redis.Extensions.Tests/StackExchange.Redis.Extensions.Tests.csproj
- tests/StackExchange.Redis.Extensions.Tests/packages.config
Added all [methods](http://redis.io/commands/#hash) to Hashes, except `HSTRLEN` which doesn't really make sense when serializing objects to redis. 
The include methods implement async API aswell as sync API.
**TODOs:**
* Documentations exists however it is not uniform with original documentation format
* No unit/integrations tests are provided with the code
* Might need some optimizations, especially the multi-get/set methods
> Added method on hashes to the StackExchangeRedisCacheClient

- src/StackExchange.Redis.Extensions.Core/Configuration/IRedisCachingConfiguration.cs
- src/StackExchange.Redis.Extensions.Core/Configuration/RedisCachingSectionHandler.cs
- src/StackExchange.Redis.Extensions.Core/Configuration/ServerEnumerationStrategy.cs
- src/StackExchange.Redis.Extensions.Core/ServerIteration/ServerEnumerable.cs
- src/StackExchange.Redis.Extensions.Core/ServerIteration/ServerIteratorFactory.cs
- src/StackExchange.Redis.Extensions.Core/StackExchange.Redis.Extensions.Core.csproj
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- tests/StackExchange.Redis.Extensions.Tests/App.config
An exception is thrown when a server becomes temporarily disconnected,
or when SCAN action is not supported. By adding these checks we are
allowing keys from other servers to be consumed.
> Check for isConnected and feature support for SCAN before calling Keys

- src/StackExchange.Redis.Extensions.Core/Configuration/ServerEnumerationStrategy.cs
- src/StackExchange.Redis.Extensions.Core/ServerIteration/ServerEnumerable.cs
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
While thinking about the implementation i ran into this scenario: no active server to server the request. In the case where there is no server to serve the Keys we should (I believe) throw an exception even when the setting is set to Ignore. The Ignore is intended to ignore single failure, not total failure do you agree? If so here it is the PR.
I also changed the setting value from Ignore to IgnoreIfOtherAvailable to convey the intention.
> Raise exception if failure is total when executing KEYS command.

- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
This fixes https://github.com/imperugo/StackExchange.Redis.Extensions/issues/97, where calls to bulk-delete Redis keys were unexpectedly executing many calls to Redis.
> Change RemoveAll to delete items in a single Redis call

- src/StackExchange.Redis.Extensions.Core/ICacheClient.cs
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
Added overloads to Get and GetAll methods to allow for a sliding window (see #112 ), as well as adding methods to allow for the updating of expiry times without calling underlying database directly and all related unit tests.
> Adding overloads to Get and GetAll to allow for sliding window

- src/StackExchange.Redis.Extensions.LegacyConfiguration/RedisCachingSectionHandler.cs
It retrieves the `ssl` config property but doesn't map it in the `GetConfig()` method.
> :bug: RedisCachingSectionHandler should map SSL setting

- src/StackExchange.Redis.Extensions.Core/Configuration/RedisConfiguration.cs
Comments for the property `Hosts` now are pluralized to reflect the possibility of having multiple hosts.
> Update RedisConfiguration.cs commenting

- samples/StackExchange.Redis.Extensions.AspNetCore.Sample/Configurations/redis.json
- src/StackExchange.Redis.Extensions.Core/Configuration/RedisConfiguration.cs
- src/StackExchange.Redis.Extensions.LegacyConfiguration/Configuration/IRedisCachingConfiguration.cs
- src/StackExchange.Redis.Extensions.LegacyConfiguration/RedisCachingSectionHandler.cs
Added SyncTimeout in Redis configuration
Fixes problems for Azure multi region:
https://azure.microsoft.com/en-us/blog/investigating-timeout-exceptions-in-stackexchange-redis-for-azure-redis-cache/
Followed docs:
https://stackexchange.github.io/StackExchange.Redis/Configuration.html
Note: I had problems with the indenting.
> Added SyncTimeout in Redis configuration

- src/StackExchange.Redis.Extensions.Core/Configuration/RedisConfiguration.cs
If static RedisConfiguration ConfigurationOptions, then if you use multiple RedisConfiguration it will be singleton and will always use the first option set resulting in bad configs.
> Fix static problem for multiple RedisConfiguration

- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
I ran some tests to make sure the string manipulation on the keys list won't add too much overhead to the method.
Here are the results:
100K records:
with prefix 326ms
without prefix 305ms
500K records:
with prefix 1620ms
without prefix 1589ms
1M records:
with prefix 3176ms
without prefix 3139ms
> Fixed SearchKeys method returning keys with KeyPrefix included

- src/StackExchange.Redis.Extensions.Core/Configuration/RedisConfiguration.cs
`StackExchange.Redis` allows to exclude certain commands which was missing when working with `StackExchange.Redis.Extensions.Core.Configuration`, in my case I'm working with a Redis like implementation that doesn't support certain commands which I needed to exclude.
To add the feature I updated `src/StackExchange.Redis.Extensions.Core/Configuration/RedisConfiguration.cs` and added a property that accepts a string array of commands to exclude.  If it exists then I pass that on to `StackExchange.Redis` `ConfigurationOptions`.
I used the sample code from the following `StackExchange.Redis` doc:
https://github.com/StackExchange/StackExchange.Redis/blob/e6be14746fcc30412d00c2ba2463fc8e43eb6f89/docs/Configuration.md#automatic-and-manual-configuration
> Added configuration option to exclude commands

- src/StackExchange.Redis.Extensions.Core/Abstractions/IRedisDatabase.cs
- src/StackExchange.Redis.Extensions.Core/ICacheClient.cs
- src/StackExchange.Redis.Extensions.Core/Implementations/RedisDatabase.cs
- src/StackExchange.Redis.Extensions.Core/Implementations/RedisDefaultCacheClient.cs
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
Hi I add Add IncrementItemt object to SortedSet, also include UT, please review.
@imperugo  #194 
Hulk
> Redis Add IncrementItemt object to SortedSet,by hulk huang;30/Aug/2019

- src/StackExchange.Redis.Extensions.Core/Configuration/RedisConfiguration.cs
- src/StackExchange.Redis.Extensions.Core/Implementations/RedisCacheConnectionPoolManager.cs
Added ProfilingSessionProvider to RedisConfiguration. RedisCacheConnectionPoolManager calls RegisterProfiler() on all new multiplexers instantiated if this is set.
> Added support for ConnectionMultiplexer.RegisterProfiler

- src/core/StackExchange.Redis.Extensions.Core/Implementations/RedisCacheConnectionPoolManager.cs
Hey guys.
recently we faced with reconnection issue and the problem was in the lazy connection initialization. 
root cause of the problem is [Exception in Lazy initialization](https://docs.microsoft.com/en-us/dotnet/framework/performance/lazy-initialization#exceptions-in-lazy-objects).
how to reproduce:
- perform connection (success)
- turn off redis
- try to connect (expected error)
- turn on redis
- try to connect (unexpected error)
fix:
set LazyThreadSafetyMode to PublicationOnly
> not cached connection errors

- src/core/StackExchange.Redis.Extensions.Core/Abstractions/IRedisDatabase.Lists.cs
- src/core/StackExchange.Redis.Extensions.Core/Implementations/RedisDatabase.List.cs
- tests/StackExchange.Redis.Extensions.Core.Tests/CacheClientTestBase.cs
Add listaddtoleftasync overloads  supports arrays operations.
> Added ListAddToLeftAsync overload method.

- src/core/StackExchange.Redis.Extensions.Core/Configuration/RedisConfiguration.cs
One of our customers ran into the following error:
```
at StackExchange.Redis.EndPointCollection.InsertItem(Int32 index, EndPoint item) in \/_\/src\/StackExchange.Redis\/EndPointCollection.cs:line 91
at System.Collections.ObjectModel.Collection`1.Add(T item)
at StackExchange.Redis.EndPointCollection.Add(String host, Int32 port) in \/_\/src\/StackExchange.Redis\/EndPointCollection.cs:line 53
at StackExchange.Redis.Extensions.Core.Configuration.RedisConfiguration.get_ConfigurationOptions()
at StackExchange.Redis.Extensions.Core.Implementations.RedisCacheConnectionPoolManager.<EmitConnection>b__7_0()
at System.Lazy`1.PublicationOnlyViaFactory(LazyHelper initializer)
at System.Lazy`1.CreateValue()
at System.Lazy`1.get_Value()
at StackExchange.Redis.Extensions.Core.Implementations.RedisCacheCon …
```
> Make ConfigurationOptions initialization thread-safe

- src/core/StackExchange.Redis.Extensions.Core/Implementations/RedisCacheConnectionPoolManager.cs
Adding missing public events InternalError and ErrorMessage from IConnectionMultiplexer, so that they are getting into logs, too.
> Include logging for additional Connection events

- src/core/StackExchange.Redis.Extensions.Core/Configuration/RedisConfiguration.cs
every ConnectionMultiplexer has  own self SocketManager  Default Not using dedicated thread-pool.
support StackExchange.Redis  new threadSocketManager mode (opt-in) to always use the regular thread-pool instead of the dedicated pool.
- Add WorkCount Configs Property
- If WorckCount is bigger than zero set new SocketManager  for ConfigurationOptions.SocketManager
> Support every ConnectionMultiplexer has  own self SocketManager 

- build.bat
- build.sh
otherwise, you can't do:
```bash
./build.sh -?
./build.sh build
```
etc.
> pass through build args

- doc/dependency-injection.md
- doc/setup-1.md
I was reviewing the library documentation and fixed some typos / spelling mistakes. Please check.
> fix documentation mistakes

- src/core/StackExchange.Redis.Extensions.Core/Implementations/RedisConnectionPoolManager.cs
The round robin connection strategy will fail in a concurrent environment, because the `Random.Next` is not thread safe. `Random` will always return `0` when the internal status is broken.
For .NET 6+, `Random.Shared` is imported and it can be used in multi-threads scenarios.
For .NET Standard 2.1, we have different workarounds to discuss.
1、Just use a new instance each time. The problem is that, if in a very short meanwhile, the results of all randoms are all the same because the seeds are all based on the same timestamp. Also, it allocates more heap memory.
2、Use a single instance with `lock`. It seems to be unacceptable as it'll make `GetConnection` much slower.
3、Use `ThreadLocal<Random>`:
```c#
private readonly ThreadLocal<Random> localRand = new(() => new …
```
> Fix `Random` thread safety.(#502)

- src/core/StackExchange.Redis.Extensions.Core/Configuration/RedisConfiguration.cs
- src/core/StackExchange.Redis.Extensions.Core/Implementations/RedisConnectionPoolManager.cs
LogerFactory passed to ConnectionMultiplexer and also reused in RedisConnectionPoolManager if loger not provided in constructor.
fix #570
> Add LoggerFactory & SocketManagerOptions to RedisConfiguration

- src/core/StackExchange.Redis.Extensions.Core/Implementations/RedisDatabase.cs
Simple PR to fix the issue https://github.com/imperugo/StackExchange.Redis.Extensions/issues/604, where the wrong type being used for scan cursor could cause a System.OverflowException in some edge cases.
> Fix: Change cursor to ulong in SearchKeysAsync for Redis SCAN (#604)
