imperugo/StackExchange.Redis.Extensions

- src/StackExchange.Redis.Extensions.Core/ICacheClient.cs
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
Added Save methods from the Redis to persist data to file system.
> Added Save methods

- .nuget/packages.config
- StackExchange.Redis.Extensions.sln
- src/StackExchange.Redis.Extensions.Protobuf/Properties/AssemblyInfo.cs
- src/StackExchange.Redis.Extensions.Protobuf/ProtobufSerializer.cs
- src/StackExchange.Redis.Extensions.Protobuf/StackExchange.Redis.Extensions.Protobuf.csproj
- src/StackExchange.Redis.Extensions.Protobuf/StackExchange.Redis.Extensions.Protobuf.nuspec
- src/StackExchange.Redis.Extensions.Protobuf/packages.config
- tests/StackExchange.Redis.Extensions.Tests/ProtobufSerializeTest.cs
- tests/StackExchange.Redis.Extensions.Tests/StackExchange.Redis.Extensions.Tests.csproj
Added protobuf extension / serializer. Fixed packages.config
> Added protobuf extension

- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
- tests/StackExchange.Redis.Extensions.Tests/Helpers/TestClass.cs
- tests/StackExchange.Redis.Extensions.Tests/StackExchange.Redis.Extensions.Tests.csproj
This will fix the broken tests.
> Added DataContract/DataMember attributes

- src/StackExchange.Redis.Extensions.Core/ICacheClient.cs
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
- tests/StackExchange.Redis.Extensions.Tests/StackExchange.Redis.Extensions.Tests.csproj
- tests/StackExchange.Redis.Extensions.Tests/packages.config
Added pub/sub methods for both synchronous and asynchronous calls on the
redis library. Included unit test.
> Added pub/sub methods

- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- src/StackExchange.Redis.Extensions.Jil/StackExchange.Redis.Extensions.Jil.csproj
- src/StackExchange.Redis.Extensions.Jil/app.config
- src/StackExchange.Redis.Extensions.Jil/packages.config
- src/StackExchange.Redis.Extensions.MsgPack/StackExchange.Redis.Extensions.MsgPack.csproj
- src/StackExchange.Redis.Extensions.MsgPack/packages.config
- tests/StackExchange.Redis.Extensions.Tests/App.config
- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
- tests/StackExchange.Redis.Extensions.Tests/StackExchange.Redis.Extensions.Tests.csproj
- tests/StackExchange.Redis.Extensions.Tests/packages.config
- Changed GetAll method to use StackExchange.Redis preferred usage
instead of generating a Lua script which was causing error. See
http://goo.gl/RyQDaJ
- Set xunit back to latest stable version instead of experimental
version
- Fixed double reference to StackExchange.Redis in packages.config,
probably due to a bad merge
- Updated all other package references to the most recent version
> Fixed GetAll method

- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
https://github.com/imperugo/StackExchange.Redis.Extensions/issues/50
https://github.com/imperugo/StackExchange.Redis.Extensions/issues/51
> Add SetMembersAsync<T> and Returned Null if ListPop is empty

- src/StackExchange.Redis.Extensions.Core/ICacheClient.cs
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
Added the new method that was included in my last pull request to the Interface.
> Added missing Interface method.

- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
Removed unnecessary usages of Dictionary<TKey, TValue> and improved the key comparison performance in the remaining cases.
The changes are self-explanatory, for a large number of keys > 10000 the gains can be substantial. A
> Performance improvements

- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
Changed ConnectionMultiplexer in StackExchangeRedisCacheClient contructor to IConnectionMultiplexer
> Changed ConnectionMultiplexer to IConnectionMultiplexer

- src/StackExchange.Redis.Extensions.Core/ICacheClient.cs
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
Add Methods in the ICacheClient : 
- SetAddAll, 
- SetAddAllAsync, 
- SetRemove, 
- SetRemoveAsync, 
- SetRemoveAll, 
- SetRemoveAllAsync
> Add Methods in the ICacheClient : 

- src/StackExchange.Redis.Extensions.Core/Configuration/IRedisCachingConfiguration.cs
- src/StackExchange.Redis.Extensions.Core/Configuration/RedisCachingSectionHandler.cs
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
Enables cache client to be initialised with key prefix which will be added to all cache keys.
> Add support for Keyspace isolation

- src/StackExchange.Redis.Extensions.Core/ICacheClient.cs
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
> Add expiry methods for AddAll

- src/StackExchange.Redis.Extensions.Newtonsoft/NewtonsoftSerializer.cs
> Fix issue #118

- src/StackExchange.Redis.Extensions.Core/ICacheClient.cs
- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
- tests/StackExchange.Redis.Extensions.Tests/CacheClientTestBase.cs
implemented
- add
- remove
- scan by score
partially fixes #124
> Basic sorted sets implementation

- src/StackExchange.Redis.Extensions.Core/StackExchangeRedisCacheClient.cs
Null check and init for ServerEnumerationStrategy
> Added null checks init

- src/StackExchange.Redis.Extensions.Core/Abstractions/IRedisCacheClient.cs
- src/StackExchange.Redis.Extensions.Core/Implementations/RedisCacheClient.cs
> Fix key prefix configuration no effect to RedisDefaultCacheClient problem.

- samples/StackExchange.Redis.Extensions.AspNetCore.Sample/Configurations/redis.json
- src/StackExchange.Redis.Extensions.Core/Configuration/RedisConfiguration.cs
- src/StackExchange.Redis.Extensions.Core/Implementations/RedisCacheConnectionPoolManager.cs
Implement configurable pool size via RedisConfiguration
Update Asp.NetCore.Sample
> Implement configurable pool size via RedisConfiguration

- src/StackExchange.Redis.Extensions.Core/Configuration/RedisConfiguration.cs
- src/StackExchange.Redis.Extensions.Core/Implementations/RedisCacheClient.cs
- src/StackExchange.Redis.Extensions.Core/Implementations/RedisDatabase.cs
Added MaxValueLength to RedisConfiguration. Changed methods:
-Add, AddAsync
-AddAll, AddAllAsync
If added value is longer than MaxValueLength, ArgumentException will be thrown.
> #204 add key size limit

- src/core/StackExchange.Redis.Extensions.Core/Abstractions/IStateAwareConnection.cs
- src/core/StackExchange.Redis.Extensions.Core/Configuration/RedisConfiguration.cs
- src/core/StackExchange.Redis.Extensions.Core/Implementations/RedisCacheConnectionPoolManager.cs
- src/core/StackExchange.Redis.Extensions.Core/Models/Delegates.cs
- src/core/StackExchange.Redis.Extensions.Core/Models/InfoDetail.cs
In order to cover the [issue#344](https://github.com/imperugo/StackExchange.Redis.Extensions/issues/344)
> - Add posibility to configure StateAwareConnection

- README.md
Other one doesn't work without permissions
> Doc link changed to public
